### ISSUE TITLE
Missing 's' in line 32, convert.py

### ISSUE THREAD

**Issue by Spica-Vir** [crystal-code-tools/crystal_functions#29]
@bcamino Hi Bruno, 

1. In line 32, script 'convert.py', 'output.atom_number' should be 'output.atom_numbers'. There is no attribute called 'atom_number'. 
2. In line 311 and 328, 'pymatgen.io.cif' should be 'pymatgen.io.xyz'. Method 'XYZ' belongs to class 'xyz'

**Comment by bcamino** [comment]
Hi @Spica-Vir , thank you so much for spotting this. Would you mind opening a PR fixing these issues? I'll merge it immediately.

Cheers,

Bruno
