### ISSUE TITLE
Dependency problem of the latest version on windows

### ISSUE THREAD

**Issue by Spica-Vir** [crystal-code-tools/crystal_functions#31]
@bcamino The latest version requires package '_curses', which is named 'windows-curses' on windows machines. Can we add the dependency to installation?

**Comment by bcamino** [comment]
@Spica-Vir, sure! Would you be able to add it to the requirements and open a PR?

**Comment by Spica-Vir** [comment]
@bcamino Hi Bruno, sorry that I am not the expert of release and installation - actually I am not sure where the installation script is. Are you happy to add a subroutine to tell the user's operation system and choose the corresponding package? Thank you.
